<?php

require_once '/home/apssouza/Projetos/jobs/tmc/include/config.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-12 at 01:42:00.
 */
class ChamadoTest extends PHPUnit_Framework_TestCase
{

	/**
	 * @var Chamado
	 */
	protected $object;
	protected $oEquip;

	public function __construct()
	{		
		$oDelete = new Delete(Chamado::TB_NAME);
		$oDelete->exec();
		parent::__construct();
		
	}

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Chamado;
		$this->oEquip = new stdClass();
		$this->oEquip->id =1;
		$this->oEquip->cliente_id =1;
		$this->oEquip->ip = '192.168.1.111';
	}


	/**
	 * @covers Chamado::abrirChamadoAutomatico
	 * @todo   Implement testAbrirChamadoAutomatico().
	 */
	public function testAbrirAutomatico()
	{
		echo $this->object->abrirAutomatico($this->oEquip);
		$this->assertGreaterThan(0, $this->object->abrirAutomatico($this->oEquip));
	}

	/**
	 * @covers Chamado::semiFecharChamado
	 * @todo   Implement testSemiFecharChamado().
	 */
	public function testSemiFecharChamado()
	{
		$this->assertGreaterThan(0, $this->object->semiFecharChamado($this->oEquip));
	}
	
	
	

}
