<?php

require_once dirname(__FILE__) . '/../../../include/config.php';

/**
 * Test class for ArrayUtil.
 * Generated by PHPUnit on 2013-02-24 at 03:02:46.
 */
class MonitorTest extends \PHPUnit_Framework_TestCase {

	protected $object;
	protected $oEquip;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Monitor();
		$this->oEquip = new stdClass();
		$this->oEquip->id =1;
		$this->oEquip->cliente_id =1;
		$this->oEquip->ip = '192.168.1.111';
	}

	
	public function testPing()
	{
		$this->assertTrue($this->object->ping('127.0.0.1'));
		$this->assertFalse($this->object->ping('192.0.0.1'));
	}

	public function testMonitora()
	{
		$this->assertTrue($this->object->monitora());
	}
	
}

?>
